In [4]:
# Establist the data directory
import pathlib 
NOTEBOOK_PATH = pathlib.Path().resolve()
DATA_DIRECTORY = NOTEBOOK_PATH / "static" / "data"

In [2]:
import fiona
fiona.supported_drivers

{'DXF': 'rw',
 'CSV': 'raw',
 'OpenFileGDB': 'r',
 'ESRIJSON': 'r',
 'ESRI Shapefile': 'raw',
 'FlatGeobuf': 'rw',
 'GeoJSON': 'raw',
 'GeoJSONSeq': 'rw',
 'GPKG': 'raw',
 'GML': 'rw',
 'OGR_GMT': 'rw',
 'GPX': 'rw',
 'Idrisi': 'r',
 'MapInfo File': 'raw',
 'DGN': 'raw',
 'PCIDSK': 'raw',
 'OGR_PDS': 'r',
 'S57': 'r',
 'SQLite': 'raw',
 'TopoJSON': 'r'}

In [5]:
import geopandas
municipalities = geopandas.read_file(
    DATA_DIRECTORY / "finland_municipalities" / "finland_municipalities_2021.gpkg"
)
municipalities.head()

,GML_ID,NATCODE,NAMEFIN,NAMESWE,LANDAREA,FRESHWAREA,SEAWAREA,TOTALAREA,geometry
0,1601000258,498,Muonio,Muonio,1904.05,133.73,0.0,2037.78,"POLYGON ((366703.026 7563861.713, 373641.706 7..."
1,1601000566,148,Inari,Enare,15056.29,2277.33,0.0,17333.62,"POLYGON ((554063.014 7746246.426, 558386.737 7..."
2,1601000428,224,Karkkila,Högfors,242.35,12.97,0.0,255.32,"POLYGON ((338515.195 6726577.401, 338539.595 6..."
3,1601000698,271,Kokemäki,Kumo,480.20,51.06,0.0,531.26,"POLYGON ((260519.503 6818726.479, 263236.792 6..."
4,1601000343,176,Juuka,Juuka,1501.70,344.87,0.0,1846.57,"POLYGON ((607203.808 7035838.978, 608878.941 7..."

In [6]:
nuts_regions = geopandas.read_file("https://gisco-services.ec.europa.eu/distribution/v2/nuts/shp/NUTS_RG_60M_2021_3035.shp.zip")
nuts_regions.head()

,NUTS_ID,LEVL_CODE,CNTR_CODE,NAME_LATN,NUTS_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,FID,geometry
0,DE149,3,DE,Sigmaringen,Sigmaringen,4.0,3,3,DE149,"POLYGON ((4272515.778 2791989.118, 4291502.208..."
1,DE211,3,DE,"Ingolstadt, Kreisfreie Stadt","Ingolstadt, Kreisfreie Stadt",4.0,2,3,DE211,"POLYGON ((4430560.572 2849070.969, 4426522.606..."
2,DE212,3,DE,"München, Kreisfreie Stadt","München, Kreisfreie Stadt",4.0,1,3,DE212,"POLYGON ((4426190.454 2780289.957, 4425325.775..."
3,DE213,3,DE,"Rosenheim, Kreisfreie Stadt","Rosenheim, Kreisfreie Stadt",4.0,2,3,DE213,"POLYGON ((4470814.937 2743662.905, 4477767.129..."
4,DE214,3,DE,Altötting,Altötting,4.0,2,3,DE214,"POLYGON ((4539906.565 2792493.475, 4525936.167..."

In [7]:
nuts_regions.to_file(DATA_DIRECTORY / "europe_nuts_regions.geojson")